name: Power BI CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  validate-powerbi-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Power BI project files
        run: |
          echo "Power BI project files:"
          find . -maxdepth 2 -type f